### ISSUE TITLE
Buggy header in pull request

### ISSUE THREAD

**Issue by Archerol** [Athari/CssGitHubWindows#13]
Diff header covers tab titles in some pages of pull request info

![screenshot from 2018-07-13 02 51 25](https://user-images.githubusercontent.com/1447642/42661472-b71bd8a6-8647-11e8-9d7d-dea6e81a5b2e.png)

**Comment by Athari** [comment]
Duplicate of #2.

@Archerol Looks like Stylus compares version field instead of updating style every time, so maybe this is the reason you didn't notice the fix. Bumped the version.
